### ISSUE TITLE
FuryBSD KDE Boots to Black Screen - SDDM Failure Loop

### ISSUE THREAD

**Issue by LenPayne** [furybsd/furybsd-livecd#136]
I installed from the 2020-Q2 KDE ISO several times across both VM and Bare Metal installs before I realized how small and silly the error was.

The fix was simple, so I'll get to that first. In the installed `sddm.conf` the user `liveuser` is setup for AutoLogin, however that user is removed during the install. When I changed the AutoLogin username to my actual username setup during install, a reboot fixed my problem.

I am not sure which solution is better, but I can propose a couple:

1. Write a small change into the Install process that updates the username in the AutoLogin process to the first user created in the `video` group, or
2. Write a small change into the Install process that removes the AutoLogin configuration entirely, or
3. Update the install script to ask "Would you like to setup AutoLogin? (yes/no)" and if yes "Which user should be logged in?"

I'm happy to work on any of the above, but don't want to move forward without direction. Any preference?

**Comment by pkgdemon** [comment]
Thank you for the report @LenPayne and very sorry for the delay.  The sddm.conf should be removed during the install by restoring the sample over top.  Perhaps they stopped shipping the sample file, and I need to change to rm?  Perhaps the location has changed? 

https://github.com/furybsd/furybsd-livecd/blob/master/furybsd-install#L29

I do plan to make sure this is fixed at least before the next ISO in July.  If you happen to solve it sooner I would be more than happy to take a pull request.  I'm embarrassed that with the covid situation, increasing obligations I haven't made time to look at this sooner.  Thank you so much for doing the initial investigation here.

**Comment by PieterSoftware** [comment]
Upstream no longer provides the `sddm.conf` file according to the port maintainer. The configuration file is still loaded if it is present but they moved to using a `sddm.conf.d` folder.
[FreshPorts - sddm 2020-02-12-15:31](https://www.freshports.org/commit.php?category=x11&port=sddm&files=yes&message_id=202002121531.01CFVP0S041402@repo.freebsd.org)

I was able to split the config file used by the installer into separate files for each section adding them to `/usr/local/etc/sddm.conf.d/`. By leaving out the entire user section everything is working and the login screen is presented after boot.

Other changes I noted is that sddm has moved its home folder in the newer versions of sddm. I suspect the scripts for creating the images need to also take this into account?

**Comment by pkgdemon** [comment]
That would explain it.  Ideally yes we would place a temporary sddm.conf the new way and clean it up afterwords.  For now I will just make a patch that removes sddm.conf from the installed system.  That should do the trick.

**Comment by pkgdemon** [comment]
https://github.com/furybsd/furybsd-livecd/commit/02a2ab1627e84e2a156329339cdd72ef4d39ef58
