### ISSUE TITLE
No way to set the date and time in Xfce?

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#152]
It appears that there is no way to set the date and time in Xfce?

![image](https://user-images.githubusercontent.com/2480569/91501408-1bb82900-e8b5-11ea-9165-d4ad94ee6ee2.png)

Furthermore, it seems impossible to set a timezone because the Timezone field has no drop-down to select something from.

![image](https://user-images.githubusercontent.com/2480569/91501565-6d60b380-e8b5-11ea-9dae-7276e4158dd7.png)

**Comment by pkgdemon** [comment]
I believe it’s due to the fact that a lot these desktops rely on systemd for that feature but I could be mistaken. Perhaps this xfce module could be replaced with something based on freebsd specific methods in the future.

**Comment by probonopd** [comment]
This seems to be the plugin that is needed:
https://www.freshports.org/x11-clocks/xfce4-datetime-plugin
