### ISSUE TITLE
Boot messages are not shown in full resolution

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#153]
Boot messages are not shown in full resolution, only in 640x480 or 800x600 pixels (4:3 ratio despite the screen being 16:9 FullHD).

This happens when booted on BIOS and UEFI-CSM systems using https://www.ventoy.net/ or without Ventoy.

**Comment by probonopd** [comment]
NomadBSD gets this right both on the Live medium and on the installed system.

**Comment by pkgdemon** [comment]
Thanks for the info.  I’ll see if that is the case with one of my systems that boots with 640x480 if nomadbsd has a way of solving.

**Comment by probonopd** [comment]
This seems machine dependent. On another machine (with a more recent EFI) the EFI sets the resolution correctly before even starting the EFI boot loader application, and there the resolution is correct throughout the boot process.

**Comment by probonopd** [comment]
On the machine in question, I now get the wrong resolution if I entered the EFI setup and then boot, and the corrrect resolution otherwise. Maybe it has to do with the fact that they picked a "failsafe" low resolution for the EFI setup program itself (American Megatrends Inc. P11-B0).

**Comment by probonopd** [comment]
Clsoing since on the particular machine (Acer Revo RL85) it now mostly works. (Only if you used the EFI setup program before it doesn't, which I guess I can live with.)
