### ISSUE TITLE
Fix start order so that service restart avahi-daemon is not needed

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#155]
By default, network services announced by Zeroconf/dns-sd are not shown:

![image](https://user-images.githubusercontent.com/2480569/91503619-743df500-e8ba-11ea-99c4-56a4b16e7e81.png)

Only after manually starting `avahi-daemon` does "Browse Network" work in the Xfce edition:

![image](https://user-images.githubusercontent.com/2480569/91502770-6f784180-e8b8-11ea-9f17-f25c23e19d6e.png)

It would be nice if `avahi-daemon` was started automatically by default.

**Comment by pkgdemon** [comment]
I might have a ticket open for mdns already.  If not it’s something I often have thought about.  We would want to enable mdns in /etc/nsswitch.conf as well as part of this change.

**Comment by pkgdemon** [comment]
Steps to do this are here https://github.com/pkgdemon/playbooks/blob/master/04-tweaks-mdns-avahi.yaml

**Comment by probonopd** [comment]
We are now shipping and enabling it, but one needs to `service avahi-daemon restart` before it starts working. Possibly a service start order issue?

How can this be fixed?

**Comment by pkgdemon** [comment]
it is definitely a server order issue caused by dhcpcd.  I have not had time to look yet.

**Comment by pkgdemon** [comment]
Fixed https://github.com/furybsd/furybsd-livecd/pull/223
