### ISSUE TITLE
Installation leads to unbootable SSD

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#156]
* Acer Revo RL85
* FuryBSD-12.1-XFCE-2020042001.iso booted from USB, in CSM Mode
* Installation to internal SATA SSD using the app shortcut on the desktop, settings left on default
* After a reboot, SATA SSD is unbootable (with and without CSM)
* SATA SSD is unbootable on other machines too

**Comment by probonopd** [comment]
Retrying, this time selecting "GPT UEFI+BIOS" in the installer menu. Shouldn't that one be the default?

**Comment by probonopd** [comment]
When manually changing the default to "GPT UEFI+BIOS" in the installer menu, then I can boot into the installed system without CSM.

So I think "GPT UEFI+BIOS" should be made the __default__.

**Comment by pkgdemon** [comment]
We use the same defaults the freebsd project uses here.  I would prefer not to change defaults without more data but it’s perhaps worth investigation or at minimum something we should not in the installation documentation on github.

**Comment by probonopd** [comment]
Cannot reproduce, closing.
