### ISSUE TITLE
Enable Synaptics touchpad

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#162]
Synaptics touchpad is not working out of the box, resulting in an unusable notebook (when one doesn't have an external mouse at hand).

Could most likely be enabled by incorporating https://wiki.freebsd.org/SynapticsTouchpad.

Machine:
Acer TravelMate B 117 (and probably lots of others)

**Comment by pkgdemon** [comment]
I would need someone with hardware to verify what is actually needed to move forward on this one.

**Comment by probonopd** [comment]
I volunteer!

**Comment by pkgdemon** [comment]
Since I don't have this hardware.  Is setting this in /etc/sysctl.conf enough to make it work?

```
hw.psm.synaptics_support="1"
```

**Comment by probonopd** [comment]
Getting

```
   sysctl: oid 'hw.psm.synaptics_support' is a read only tunable
   sysctl: Tunable values are set in /boot/loader.conf
```

when trying to run `sysctl hw.psm.synaptics_support="1"` on the booted system. Will try `set hw.psm.synaptics_support="1"` at the bootloader prompt of the Live ISO next.

**Comment by probonopd** [comment]
That alone did not do it, neither on the console nor in Xorg. Maybe more needs to be done. https://wiki.freebsd.org/SynapticsTouchpad

**Comment by pkgdemon** [comment]
You might need this.  Which I haven’t merged to master yet.  

https://github.com/furybsd/furybsd-livecd/commit/5f73ac2ad166837e8eaa88899bfeb0a5b230e20d

Installing this package, and enabling at boot allowed my Lenovo Yoga c930 touchpad, and touchscreen to work out of box with libinput to which if I am not mistaken replaces synaptics anyway for xorg, wayland.

**Comment by probonopd** [comment]
Acer TravelMate B 117 is working now out of the box with master! Tested with Lumina. :+1:

**Comment by pkgdemon** [comment]
Nice!  Thank you confirming.  I'm loving having my Lenovo Yogo C930 working as well.
