### ISSUE TITLE
CI builds (stalls at: bsdinstall distfetch)

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#163]
I think it would be very useful to set up CI builds, e.g., on [Cirrus CI](https://cirrus-ci.com/).

I have tried to set it up there and the script begins to run, but then stalls without any CPU activity forever at the `bsdinstall distfetch` step.

Do you have an idea why this might be?

https://cirrus-ci.com/task/4556905714548736?command=test#L57

**Comment by pkgdemon** [comment]
Interesting.  Does cirrus-ci allow ssh for further troubleshooting?

**Comment by probonopd** [comment]
https://github.com/cirruslabs/cirrus-ci-docs/issues/432

**Comment by probonopd** [comment]
Just a wild guess, it doesn't like the FreeBSD Installer "GUI". Is there a way to get "normal" console output instead of the blue-background textual user interface?

**Comment by probonopd** [comment]
Removing bsdinstall solves this. Will be addressed in my upcoming PR.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
