### ISSUE TITLE
Move some packages out of packages.common to allow smaller images

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#170]
Things like

```
firefox
icons-tango
zenity
```

pull in the Gtk/Gnome stack, I think they should not be in `packages.common` so that one can build a truly minimal image without those dependencies. Instead, these packages could go to the desktop-specific `packages.*` lists.

The KDE Plasma one, for example, wouldn't use `icons-tango` but `kf5-breeze-icons`, and the Xfce one would probably want `xfce-icons-elementary`.

If you are OK with this change, then I can prepare a PR.

**Comment by pkgdemon** [comment]
I use zenity and soon to be yad for all the related tools I develop such as the xorg tool, wifi tool. Tango icons are used for xdg entries for those tools.  Perhaps xdg icon entries could be made more generic to resolve that issue.  Then It wouldn't mind the idea as much if we could keep a packages.common for desktop specific tools.

**Comment by pkgdemon** [comment]
I think I see where you are going since your main interest seems to be lumina.  I'm sure you don't want to ship a bunch of GTK related tools with it.  I would just keep in mind I guess that you would need to redevelop QT based tools for xorg/wifi using dialog, qt or some other solution wifi if you don't want to bundle zenity/yad with what are you are trying to assemble around Lumina.  I had a whole list of things I was going to build out like a firewall assistant, a bunch of other things.  I had the concept of using ansible playbooks originally which I have a collection of but that might be a bit much.

**Comment by probonopd** [comment]
> I use zenity and soon to be yad for all the related tools I develop such as the xorg tool, wifi tool. Tango icons are used for xdg entries for those tools.

Wouldn't the goal to be not to need any such "special" GUIs anymore because everything "just works" right out of the box, like on an Ubuntu Live CD?

**Comment by pkgdemon** [comment]
I am okay with going this direction.  Currently wifi, xorg are not practical to fully automate the way you describe, or at least I haven't found a way from any 3rd party that works that doesn't aggravate me other than what I have created.  But yes I don't want to have to make tools for everything.  If we can make it wifi/xorg work better without special GUI scripts I built around yad/zenity then we can deprecate the old tooling for sure, and not just be limited to excluding for lumina.  Right now the two tools I include on desktop are simply to make my life easier to get my wifi working on various laptops, graphics working on various other systems.  Still a common wifi try will be needed.  I don't see a way around that and there is no tool that will work for us we have to make one unless you can maybe get dhcpcd-ui working.  It has both a QT/GTK front end.  But I think encryption support might be very simple limited, compared to what wpa-gui offers.

**Comment by probonopd** [comment]
Will be addressed in my upcoming PR, at least partially.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
