### ISSUE TITLE
Improve speed by not running 'chflags -R noschg' twice?

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#171]
These operations take relatively long time, are they really needed? And do we really need them twice?

https://github.com/furybsd/furybsd-livecd/blob/f9c2c342ad2b8b09bbb364b248b577b4c3369f80/build.sh#L90

https://github.com/furybsd/furybsd-livecd/blob/f9c2c342ad2b8b09bbb364b248b577b4c3369f80/build.sh#L288

**Comment by pkgdemon** [comment]
I'll take a PR for this.  Seems like a good idea.  I may have had a reason for it but I don't recall what it was.

**Comment by probonopd** [comment]
I have removed it in both places and don't see any ill effects, at least not in Live mode.

**Comment by probonopd** [comment]
Will be addressed in my upcoming PR.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
