### ISSUE TITLE
Proposal: Use on-the-fly pkg for uzip overlays

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#172]
Currently, various files get copied into the uzip.

I would like to propose a cleaner approach:

1. Everything that gets copied into the uzip goes into a filesystem tree within `overlays/uzip/<pkg-name>/files`. For example, `/etc/fstab` might go to `overlays/uzip/<pkg-name>/files/etc/fstab`
1. A very simple boilerplate `manifest` file is added to `overlays/uzip/<pkg-name>`
1. `build.sh` generates temporary on-the-fly `pkg` files for each of the directories specified in `settings/overlays.common` that reside in in `overlays/uzip/` and installs them alongside the other packages

This approach would allow for:

1. Desktop-specific `settings/overlays.*` to be introduced easily
1. Clean uninstall of packages at the time when the system is installed to disk
1. User can always decide to uninstall certain packages, e.g., the wallpapers

I have implemented this in the https://github.com/probonopd/furybsd-livecd/tree/pkg `pkg` tree. I have successfully built a working Lumina ISO with this.

What do you think?

I have not moved _all_ files to the new approach yet, but would do this in case you agree.

**Comment by pkgdemon** [comment]
This sounds interesting.  I would need to take some time to build your version and bisect it a little further I think.

**Comment by pkgdemon** [comment]
It sounds a bit like debian live-build's approach where you have to add entries for the overlays you want?

**Comment by pkgdemon** [comment]
The goal is to be able to exclude any specific overlays you don't want?  I would assume this means you have to populate a manifest manually each time you want to add a new file?

**Comment by probonopd** [comment]
The goal is that you can select, per desktop, which overlays that get put into the image. And since each overlay gets onto the system by the way of a (on-the-fly generated) pkg, it can cleanly be removed.

**Comment by pkgdemon** [comment]
I am okay with going this direction if you can make it work.

**Comment by probonopd** [comment]
Booting a Lumina ISO made this way as we speak :-)
Btw, do you hang out on IRC?

**Comment by pkgdemon** [comment]
> Booting a Lumina ISO made this way as we speak :-)
> Btw, do you hang out on IRC?

I haven't in a while.  I have a quarrel client going but I don't check it often enough.  I'm on telegram and we have a FuryBSD channel listed on the website https://t.me/furybsd.

**Comment by pkgdemon** [comment]
If you can get telegram feel free to direct message.

**Comment by probonopd** [comment]
https://github.com/probonopd/furybsd-livecd/tree/more-pkg is starting to make use of this concept, please have a look at the `overlays/uzip` structure. Every directory there gets converted into a pkg on-the-fly and installed _if_ it is requested in the corresponding `settings/overlays.*` file. I hope this makes sense.

(Sorry but for privacy reasons I won't touch a service like Telegram that requires a mobile phone number to sign up. I've joined `#furybsd` on FreeNode for now. Maybe a bridge between Telegram and that channel could be set up, e.g., using  [matterbridge](https://github.com/42wim/matterbridge).)

**Comment by pkgdemon** [comment]
> https://github.com/probonopd/furybsd-livecd/tree/more-pkg is starting to make use of this concept, please have a look at the `overlays/uzip` filesystem tree structure. Every directory there gets converted into a pkg on-the-fly and installed _if_ it is requested in the corresponding `settings/overlays.*` file. I hope this makes sense.
> 
> (Sorry but for privacy reasons I won't touch a service like Telegram that requires a mobile phone number to sign up. I've joined `#furybsd` on FreeNode for now. Maybe a bridge between Telegram and that channel could be set up, e.g., using [matterbridge](https://github.com/42wim/matterbridge).)

Joined IRC channel my handle is malco_2001.

**Comment by probonopd** [comment]
As discussed on IRC, PR forthcoming.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
