### ISSUE TITLE
Make it easier to get the date and time from the network

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#181]
Make it easier to get the date and time from the network without having to resort to command line tools.

Maybe write a tiny GUI tool that asks the user for permission to do a geolocation over the network, and then set the timezone accordingly, and finally get the network time and set it.

(Note: I am especially sensitive to this because the battery in one of my test systems is depleted, hence the clock is always wrong, and without a correct clock Firefox refuses to load pages.)

**Comment by pkgdemon** [comment]
I normally enabled the following in rc.conf on all of my systems after install:

ntpd_enable="YES"
ntpdate_enable="YES"

Perhaps we should enable these services by default?  I think that would be very reasonable.

**Comment by pkgdemon** [comment]
In addition to that we can probably use the timezone hook in dhcpcd since I bundle that and it is the default DHCP client.

https://github.com/rsmarples/dhcpcd/tree/master/hooks

**Comment by probonopd** [comment]
Yes. We should do that. Some ARM systems (Raspberry Pi) don't even have a clock battery.

**Comment by probonopd** [comment]
Implemented in https://github.com/furybsd/furybsd-livecd/commit/ac286ae77446a04f61e37afa36da0ef1d5c5d614
