### ISSUE TITLE
GNUstep edition with Rik theme

### ISSUE THREAD

**Issue by dszidi** [furybsd/furybsd-livecd#189]
Can we have a GNUstep spin with the Rik theme from this repo?

https://github.com/BertrandDekoninck/rik.theme/blob/master/newscreen.png

**Comment by probonopd** [comment]
Is the Rik theme in `pkg`?

**Comment by probonopd** [comment]
Similarly:

* Display Manager: http://multixden.blogspot.com/2009/07/login-manager-for-gnustep.html?
* Window Manager: Window Maker http://wiki.gnustep.org/index.php/Window_manager?

**Comment by probonopd** [comment]
A few apps: http://www.gnustep.org/softwareindex/

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/93641881-608b3780-f9fd-11ea-9f85-029b70cd04d1.png)

**Comment by probonopd** [comment]
I guess we need to cut down the number of "Docks" somehow.

![image](https://user-images.githubusercontent.com/2480569/93643404-4141d980-fa00-11ea-8b27-2b2e3f93da06.png)

**Comment by pkgdemon** [comment]
The extra docks are created by windowmaker which is it's own thing it's not really integrated into gnustep.  I am not sure why it's recommend in so many guides to be used along with gnustep when it provides it's own dock, etc.

https://github.com/trunkmaster/nextspace includes it's own window manager called workspace.  Maybe that could be pulled in or something similar could be used, or a lighter window manager that doesn't create a dock?  

Here is an example of me launching gnustep with mutter to remove the windowmaker extra dock.
https://www.youtube.com/watch?v=X1iWhSo1Oys&app=desktop.

**Comment by probonopd** [comment]
[mutter](https://www.freshports.org/x11-wm/mutter) has a dependency on `libgnome-desktop-3.so`, not something we should strive for in this edition...

**Comment by probonopd** [comment]
https://github.com/AlessandroSangiuliano/uroswm seems to be a window manager written in ObjC for the GNUstep desktop, however I have [not yet succeeded in making it work properly](https://github.com/AlessandroSangiuliano/uroswm/issues/2). Maybe @AlessandroSangiuliano can give us some hints?

**Comment by pkgdemon** [comment]
Maybe hiding the windowmaker dock is an alternative also if it can be done?  https://wmaker-user.windowmaker.narkive.com/awao1ziO/hiding-the-dock

**Comment by probonopd** [comment]
We have _something_: https://github.com/probonopd/furybsd-livecd/releases/download/continuous/FuryBSD-12.1-GNUSTEP-amd64.iso - still expect lots of rough edges. Any hints on how to improve are highly welcome.

**Comment by pkgdemon** [comment]
@probonopd I believe slim is a fork of login.app.

**Comment by probonopd** [comment]
This is what we currently have:

![image](https://user-images.githubusercontent.com/2480569/93686114-aac6f400-faa3-11ea-805a-210ecf61dcc2.png)

**Comment by probonopd** [comment]
This is where we stand now:

![image](https://user-images.githubusercontent.com/2480569/93719645-7ae72180-fb73-11ea-9837-137602f9f83f.png)

**Comment by probonopd** [comment]
Lacking apps
* Web browser. (Ideally without Gtk, and ideally AppKit+WebKit based.)
* Screenshot tool. (Should work on Alt-Shift-3, Alt-Shift-4,...)

**Comment by probonopd** [comment]
Slowly it's beginning to come together...

![image](https://user-images.githubusercontent.com/2480569/93935441-262edc80-fd14-11ea-8f7b-000a61f047e2.png)

**Comment by pkgdemon** [comment]
Closing since the fork has been created with the edition.  New issues around this should be tracked in the fork.

**Comment by probonopd** [comment]
Just in case you are seeing this looking for the GNUstep edition:
It has been moved to https://github.com/probonopd/LIVEstep since it is still in the very early stages, not ready for inclusion on FuryBSD proper at this point.
