### ISSUE TITLE
Touchpads not working on some modern laptops

### ISSUE THREAD

**Issue by pkgdemon** [furybsd/furybsd-livecd#19]
Lenovo Yogo C930 not working

**Comment by johnnagro** [comment]
this FreeBSD bug/patch seems to be related: https://reviews.freebsd.org/D16698

**Comment by johnnagro** [comment]
Lenovo Ideapad 720s not working

**Comment by pkgdemon** [comment]
This should have been resolved already with the Q3 image.  The package is applied.  My Lenovo Yoga C930 touchpad, and touchscreen now work.
