### ISSUE TITLE
Continuous builds: ntpdate runs too early

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#204]
Continuous builds: `ntpdate` runs too early, before we have an IP address. As a result, the time does not get set.

How to fix this?

**Comment by pkgdemon** [comment]
This is related to the avahi ticket.  Same issue.

**Comment by pkgdemon** [comment]
Potential fix in this PR. https://github.com/furybsd/furybsd-livecd/pull/223   I would like to do more testing but I think I will merge soon.

**Comment by pkgdemon** [comment]
I will follow up with what has been tested in the proposed fix.

**Comment by pkgdemon** [comment]
Fixed https://github.com/furybsd/furybsd-livecd/pull/223
