### ISSUE TITLE
Terminal.app

### ISSUE THREAD

**Issue by dszidi** [furybsd/furybsd-livecd#211]
For the GNUstep spin, please include Terminal.app in the build. Also Terminal.app should be GWorkSpace.app's default terminal emulator, not xterm.

**Comment by probonopd** [comment]
In the latest build it is installed and configured - but it cannot find the service... for whatever reason

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/93935786-ad7c5000-fd14-11ea-8dfe-f0778f2cb737.png)

**Comment by pkgdemon** [comment]
Closing since the fork has been created with the edition.  New issues around this should be tracked in the fork.
