### ISSUE TITLE
Non GNUstep apps inconsistent results

### ISSUE THREAD

**Issue by dszidi** [furybsd/furybsd-livecd#213]
I tested the continuous build circa September 23rd and tried installing non GNUstep apps to see the new behavior.

**Apps tested:**  
- Inkscape (GTK), 
- VSCode (Electron/GTK), 
- KeepassXC (Qt)  

**Results:**
- Not all applications correctly installed themselves into /Local/Applications. 
- VSCode actually installed two. One for the editor and the other was some utility. 
- KeepassXC never installed anything.
- Inkscape.app throws an error on launch. "Error Inkscape is Hung"

Since technically two of the apps were gtk and only one of them threw the error, I suspect that problem is probably specific to Inkscape

**Comment by probonopd** [comment]
Thanks @dszidi. For now in order not to clutter the FuryBSD issue tracker I'd say let's move GNUstep discussion to https://github.com/probonopd/LIVEstep//issues. THis way it is easier to keep apart general issues with furybsd-livecd from GNUstep specific issues.

**Comment by probonopd** [comment]
When this happens, can you please manually run `desktop2app /usr/local/share/applications/APPNAME.desktop`? It _should_ create an `APPNAME.app` wrapper in your current working directory if invoked this way. Strangely this seems to work (more often)...

**Comment by probonopd** [comment]
To debug this, run in a terminal:

```
sudo service desktop2app stop
sudo desktop2app
```

Keep this terminal open while you `pkg install` applications in a second terminal.
This way you see what is going on.

**Comment by pkgdemon** [comment]
Closing since the fork has been created with the edition.  New issues around this should be tracked in the fork.
