### ISSUE TITLE
Move installer into it's own pkg

### ISSUE THREAD

**Issue by pkgdemon** [furybsd/furybsd-livecd#219]
Make it easier for others contributing to find it.  Maybe there is a case also we will want the installer in the future after install as well and not just in live-settings.

**Comment by probonopd** [comment]
Would it be worthwhile to try getting it into its own port?

**Comment by pkgdemon** [comment]
> Would it be worthwhile to try getting it into its own port?

Yes I definitely think there is some value in working towards that.  I plan to dig in and see if I can help make this a little less "furybsd" specific with you by fixing some related tickets which need created.  See my comment here for the first example.  https://github.com/furybsd/furybsd-livecd/issues/190#issuecomment-692685342 There are some conditions that will not exist on FreeBSD we should fix up first in my opinion before attempting.  But definitely yes.

**Comment by probonopd** [comment]
If we can get pkg scripts to work on our "transient pkgs", then we could move all FuryBSD-related logic to the
[pkg-deinstall script](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/pkg-deinstall.html) of the `furybsd-live-settings` pkg.
