### ISSUE TITLE
XFCE missing volume mixer and some other plugins

### ISSUE THREAD

**Issue by pkgdemon** [furybsd/furybsd-livecd#29]
Need to make sure these are added to packages.xfce

**Comment by dpostolov** [comment]
Hi! Please add pkgs xfce4-mixer and xfce4-xkb-plugin for keyboard layouts.

**Comment by pkgdemon** [comment]
Partially addressed here:

I need to look to see what is the difference between mixer plugin, and xfce4-mixer to ensure one is not more functional over the other.  For this image the mixer plugin was chosen.

https://github.com/furybsd/furybsd-livecd/releases/tag/12.0-XFCE-11-09-2019-01

**Comment by pkgdemon** [comment]
I cannot include the xfce4-mixer because it doesn't work.  Currently the xfce4 mixer plugin pkg that is included instead works.  I made a patch to include the xkb plugin.  https://github.com/furybsd/furybsd-livecd/commit/59f89c2069805a221d5305b128f91f4adbecb37f
This will be included in next ISO.
