### ISSUE TITLE
Request for feature: add FreeBSD patchsets to ISO

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#32]
Is it possible to add FreeBSD patchsets to FuryBSD ISO?

To avoid the manual commands:
freebsd-update fetch
freebsd-update install

**Comment by pkgdemon** [comment]
Done.  Will be included in next ISO.

https://github.com/furybsd/furybsd-livecd/commit/615ca861b4f7b6ce34e687d945a10bd4e1c8abc4
