### ISSUE TITLE
intel drm-kmod configure bug on 22-Nov-2019-01 image

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#54]
FuryBSD-12.0-XFCE-11-22-2019-01

Hardware: Intel NUC5PPYH CPU Intel N3700 Braswell & Intel NUC DN2820FYKH CPU Intel N2830 BayTrail-M.

Try to select: Intel drm-kmod video driver and after the message Xorg now will be restarted, the next error on screen:

KLD i915kms.ko depends on drmn - not available or version mismatch
linker_load_file: /boot/modules/i915kms.ko - unsupported file type

https://yadi.sk/i/pMbsueOgmHIFUw

The workaround: use scfb video driver in EFI mode. There is no this problem with Intel drm-kmod video driver at previous versions of FuryBSD, but Intel kmod-drm is not for me, because Xfce screensaver to sleep my display after screensaver starts in intel-drm video driver mode.

**Comment by pkgdemon** [comment]
Thanks for reporting.  I have confirmed the issue.  I believe it might be that /boot/modules is not in the same file system as /boot/kernel.  After looking into what GhostBSD is doing I think I am going to spin up another small image rework with nullfs to address it.  Might be another week or so but the rework will address this problem.

**Comment by pkgdemon** [comment]
This image fixes:

https://github.com/furybsd/furybsd-livecd/releases/tag/12.0-XFCE-11-23-2019-01
