### ISSUE TITLE
GhostBSD Network Manager does not respond to mouse clicks on menu items after OS install

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#56]
FuryBSD-12.0-XFCE-11-23-2019-01

Hardware: Intel NUC5PPYH CPU Intel N3700 Braswell & Intel NUC DN2820FYKH CPU N2830 BayTrail-M.

GhostBSD Network Manager works correctly in LiveUSB mode and responds to mouse clicks on menu items, but after FuryBSD installation complete and reboot, login to OS, GhostBSD Network Manager does not respond to mouse clicks on menu items on Wired Connection: Disable/Enable and WiFi: Enable/Disable.

**Comment by pkgdemon** [comment]
Thanks for the report.  I have a feeling doas.conf may be missing.  I will take a look, and make another image ASAP.

**Comment by dpostolov** [comment]
Hi! Joe, please e-mail me dpostolov@yandex.ru and I would like to discuss with you the FuryBSD topic.

**Comment by pkgdemon** [comment]
> Hi! Joe, please e-mail me [dpostolov@yandex.ru](mailto:dpostolov@yandex.ru) and I would like to discuss with you the FuryBSD topic.

Email sent.  Finishing up ports updater first, and will have image with fixes.  This should also fix so existing installs can get updates without having to reinstall once complete.

**Comment by pkgdemon** [comment]
Fixed in new ISO https://github.com/furybsd/furybsd-livecd/releases/tag/12.0-XFCE-11-29-2019-01
