### ISSUE TITLE
GhostBSD Network manager need more testing for switching between Ethernet and WiFi connections

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#69]
GhostBSD Network manager need more testing for switching between Ethernet and WiFi connections if both connections are available.

Video: https://yadi.sk/i/3IAl4FhIl_CUpA

P.S. Sorry for the large video size, my phone rec video in .mp4 mode.

**Comment by dpostolov** [comment]
Probably this was bug in my WiFi Card (problem with its ID and hardware). Now the WiFi Card(s) is unplugged from Intel NUC(s) and all OK. Only Ethernet connection is available in my systems. This bug for close.

**Comment by pkgdemon** [comment]
Closing this one as requested
