### ISSUE TITLE
Xfce screensaver need more testing (not always start)

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#70]
Sorry for my bad English... Xfce screensaver need more testing (not always start). (Start Floating Xfce after 10 minutes not at always time). This is in intel-drm video driver mode. Hardware: Intel NUC5PPYH CPU N3700 Braswell & Intel NUC DN2820FYKH CPU N2830 BayTrail-M.

**Comment by dpostolov** [comment]
How to reproduce:

1. Select intel-drm video driver in FuryBSD Installer.
2. Install FuryBSD.
3. Reboot and login.
4. pkg install xfce4-power-manager and to configure it: Display / Switch off after: Never and Put to sleep after: Never, but Display Power Management: Enable (else my TV Supra in Display HDMI mode power off after some time of work).
5. Configure Xfce screensaver: Lock screen: Disable, Theme: Floating Xfce, Activate screensaver when computer is idle: after 10 minutes. Enable screensaver: On.
6. Screensaver successfully works after 10 min idle, but if reboot and re-login: screensaver don't works.
7. How it made works: again configure screensaver: Enable screensaver: On and close window. But after reboot problem return.

8. Workaround: maybe help use scfb video driver. This is need more testing in screensaver Floating Xfce mode.

**Comment by dpostolov** [comment]
Workaround: Disable Xfce screensaver and Disable Xfce screensaver at Xfce Application autostart. Then pkg install xscreensaver, run at (as daemon) and Enable xscreensaver in Xfce Application autostart. Reboot. Profit!

**Comment by pkgdemon** [comment]
The XFCE screensaver pkg was removed for Q3 ISO.  I forgot to close this ticket when the change was made.  https://github.com/furybsd/furybsd-livecd/issues/132
