### ISSUE TITLE
New install script broken (KDE iso)

### ISSUE THREAD

**Issue by jbwyatt4** [furybsd/furybsd-livecd#79]
Hello, FuryBSD was posted on HN. https://news.ycombinator.com/item?id=22104235

I gave the KDE version a try with virt-manager on Manjaro. I got to the new user setup.

I followed the suggestions in the handbook (including wheel group), it kept saying there was an error with creating a user, but not reporting what the error is.

Moved on with the install. First boot stays in the terminal. Does not show the KDE login screen.

Does not let me login into any of the users I created except root.

**Comment by pkgdemon** [comment]
Thank you for the feedback @jbwyatt4 I may have to consider a new installer based around pc-sysinstall, and gbi.  I've seen some other reports on the forums about users having issues saving passwords with spaces.  Not sure if this is what you are running into, but either way it's seems the current useradd tool from FreeBSD is not intuitive enough for the growing audience looking at FuryBSD.

**Comment by jbwyatt4** [comment]
It wasn't, I did select bash as the default shell with a one character username.

**Comment by probonopd** [comment]
Is this still relevant with the continuous builds or can it be closed?

**Comment by pkgdemon** [comment]
Fixed https://github.com/furybsd/furybsd-livecd/commit/94576014d0b93d0b81192d1fbd3a616de1208d85
